baseurl = "/"
languageCode = "en-us"
Title = "GLLMT TEST"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright Gllmt"

theme = "hugo_theme_pickles"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "pgllmt"
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  author = "Pierre ✌️"
  authorwebsite = "example.com"
  avatar = "/images/avatar.jpg"
  # contact = "Your contact link (ex. mailto:foo@example.com)"
  bio = "FRONT-END / CREATIVE DEVELOPER, design, typography, photography, minimalism. Former intern at @mashvp."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

